# Generated by Django 6.0.4 on 2026-04-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
