# Generated by Django 6.0.4 on 2026-04-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cancha_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='precio_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
