# Generated by Django 6.0.4 on 2026-04-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id_cancha', models.AutoField(db_column='Id_Cancha', primary_key=True, serialize=False)),
                ('nombre_cancha', models.CharField(db_column='Nombre_Cancha', max_length=20)),
                ('capacidad_cancha', models.IntegerField(db_column='Capacidad_Cancha')),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'cancha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id_complejo', models.AutoField(db_column='Id_Complejo', primary_key=True, serialize=False)),
                ('nombre_complejo', models.CharField(db_column='Nombre_Complejo', max_length=100)),
                ('ubicacion_complejo', models.CharField(db_column='Ubicacion_Complejo', max_length=200)),
            ],
            options={
                'db_table': 'complejo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('id_estado_pago', models.AutoField(db_column='Id_Estado_Pago', primary_key=True, serialize=False)),
                ('estado_pago', models.CharField(db_column='Estado_Pago', max_length=50)),
                ('descripcion', models.TextField(db_column='Descripcion')),
            ],
            options={
                'db_table': 'estado_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id_estado_reserva', models.AutoField(db_column='Id_Estado_Reserva', primary_key=True, serialize=False)),
                ('estado_reserva', models.CharField(db_column='Estado_Reserva', max_length=50)),
                ('descripcion', models.TextField(db_column='Descripcion')),
            ],
            options={
                'db_table': 'estado_reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(db_column='Id_Metodo_Pago', primary_key=True, serialize=False)),
                ('nombre_metodo', models.CharField(db_column='Nombre_Metodo', max_length=50)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'db_table': 'metodo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(db_column='Id_Pago', primary_key=True, serialize=False)),
                ('monto_pago', models.DecimalField(db_column='Monto_Pago', decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(db_column='Fecha_Pago')),
            ],
            options={
                'db_table': 'pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(db_column='Id_Reserva', primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField(db_column='Fecha_Reserva')),
                ('hora_inicio', models.TimeField(db_column='Hora_Inicio')),
                ('hora_fin', models.TimeField(db_column='Hora_Fin')),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='Id_Rol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='Nombre_Rol', max_length=20)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCancha',
            fields=[
                ('id_tipo_cancha', models.AutoField(db_column='Id_Tipo_Cancha', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'db_table': 'tipo_cancha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(db_column='Id_Usuario', primary_key=True, serialize=False)),
                ('nombre_usu', models.CharField(db_column='Nombre_Usu', max_length=20)),
                ('apellido_usu', models.CharField(db_column='Apellido_Usu', max_length=20)),
                ('telefono', models.IntegerField(blank=True, db_column='Telefono', null=True)),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('contrasena', models.CharField(db_column='Contrasena', max_length=20)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id_usuario_rol', models.AutoField(db_column='Id_Usuario_Rol', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_rol',
                'managed': False,
            },
        ),
    ]
